### ISSUE TITLE
박정민 TODO

### ISSUE THREAD

**Issue by plou102** [Front-end-Components/market-mong-nyang#2]
12 - 12 - 월
- [x] 구매 확정 api 연결
- [x] 주문 상태 바꾸기 (구매 완료, 구매 확정, 주문 취소)
- [x] 구매 확정에 따른 버튼 유무
- [x] 주문 취소 api 연결
- [x] 주문 상세 페이지

12 - 13 - 화
- [x] 주문 상세 페이지 연결
- [x] 상세 페이지 api 연결
- [x] 상세 페이지 구조 잡기

12 - 14 - 수
- [x] 주문 상세 페이지
- [x] 주문 내역 썸네일 주소 바꾸기

12 - 15 - 목
- [x] 상세 페이지 썸네일 주소 바꾸기
- [x] 상세 페이지 완성
- [x] 구매 내역 페이지 (구매 완료 / 구매 확정 - 구매가 완료 되었습니다.   주문 취소 - 주문이 취소 되었습니다.)

12 - 16 - 금
- payment
  - [x] account component
  - [x] productDetail 상품이름, 가격, 개수 등등 가져와서 채우기

12 - 18 - 일
- myOrder
  - [x] 달력 추가 (날짜 별로 볼 수 있도록 하기)
  - [x] 개수 조정 (한개씩 결제 되기 때문에 주문내역에 같은 상품이 1개씩 쌓임 -> 같은 날짜 같은 상품이름 중복 제거)
 - myOrderDetail
   - [x] 구매한 개수 추가
   - [x] 최종 주문 금액 수정
- paymentItem
  - [x] 제품 상세 페이지에서 한가지 제품 구매할 때
  - [x] 장바구니 페이지에서 여러가지 제품 구매할 때 분리하기
  - [x] 구매한 후 주문 내역으로 이동
- payment
  - [x] 주문 상품 수정
- [x] try catch 추가하기

12 - 19 - 월
- myorder
 - [x] 상태 버튼 클릭 시 상태 가이드 변화 및 버튼 숨기기
- payment
 - [x] 결제 시 장바구니에서 결제한 상품 제거
